In [ ]:
#!pip install pandas openpyxl

In [2]:
import pandas as pd
df = pd.read_excel('charts_group_project.xlsb')
df.head()

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name
0,44875,au,169,280161,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up
1,44875,be,182,59603,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up
2,44875,ie,184,46016,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up
3,44875,cz,198,43421,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up
4,44868,be,159,62915,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up

In [1]:
list_of_lists = [elem.replace("[","").replace("]","").replace("'","").split(",") for elem in df['artist_genres'].unique()] 
[ elem.a for elem in list_of_lists ]

NameError: name 'df' is not defined

In [23]:
import ast

def safe_eval_genre(s):
    try:
        return ast.literal_eval(s)
    except:
        return []

df['artist_genres_list'] = df['artist_genres'].apply(safe_eval_genre)

In [25]:
df['artist_genres_list']

0                  [pop rap, pop, pop dance, dance pop, edm]
1                  [pop rap, pop, pop dance, dance pop, edm]
2                  [pop rap, pop, pop dance, dance pop, edm]
3                  [pop rap, pop, pop dance, dance pop, edm]
4                  [pop rap, pop, pop dance, dance pop, edm]
                                 ...
1048570    [permanent wave, modern rock, rock, garage roc...
1048571    [edm, pop, metropopolis, uk pop, electropop, i...
1048572      [neo mellow, contemporary vocal jazz, jazz pop]
1048573                         [viral pop, pop, neo mellow]
1048574    [stomp and holler, chamber pop, indie rock, in...
Name: artist_genres_list, Length: 1048575, dtype: object

In [26]:
genre_map = {
    "pop": ["pop", "pop rap", "pop dance", "dance pop", "electropop", "uk pop", "viral pop", "canadian pop"],
    "hip hop/rap": ["hip hop", "rap", "trap", "pop rap", "latin hip hop", "southern hip hop", "gangster rap"],
    "electronic/dance": ["edm", "electro house", "house", "progressive house", "tropical house", "trance", "complextro"],
    "latin": ["reggaeton", "bachata", "cumbia", "latin pop", "urbano latino"],
    "r&b/soul": ["r&b", "neo soul", "contemporary r&b", "chill r&b", "pop r&b"],
    "rock": ["rock", "pop rock", "modern rock", "alternative rock", "indie rock"],
    "country/folk": ["country", "country pop", "folk pop"],
    "global/regional": ["k-pop", "j-pop", "mandopop", "italian pop", "french pop"],
    "alternative/indie": ["indie pop", "indie poptimism", "bedroom pop", "alt z", "art pop"],
    "reggae/dancehall": ["dancehall", "moombahton", "tropical"]
}

In [27]:
def assign_main_genre(genres):
    if not genres:
        return "Other"
    
    genres = [g.lower() for g in genres]
    
    for main_genre, subgenres in genre_map.items():
        for sub in subgenres:
            if any(sub == g or sub in g for g in genres):
                return main_genre.capitalize()
    return "Other"

In [28]:
df['main_genre'] = df['artist_genres_list'].apply(assign_main_genre)

In [29]:
df.head()

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name,artist_genres_list,main_genre
0,44875,au,169,280161,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
1,44875,be,182,59603,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
2,44875,ie,184,46016,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
3,44875,cz,198,43421,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop
4,44868,be,159,62915,0nrRP2bk19rLc0orkWPQk2,['Avicii'],"['pop rap', 'pop', 'pop dance', 'dance pop', '...",247426,False,Wake Me Up,"[pop rap, pop, pop dance, dance pop, edm]",Pop

In [44]:
genres_df = pd.DataFrame({"genre_id": [i for i in range(1, len( list( genre_map.keys() ) ) +1)],"main_genre": list(genre_map.keys())})
genres_df

   genre_id         main_genre
0         1                pop
1         2        hip hop/rap
2         3   electronic/dance
3         4              latin
4         5           r&b/soul
5         6               rock
6         7       country/folk
7         8    global/regional
8         9  alternative/indie
9        10   reggae/dancehall

In [45]:
genres_df.to_csv("genre.csv", index=False, encoding="utf-8", sep=";")

In [54]:
df["main_genre"] = df["main_genre"].str.lower()
genres_df["main_genre"] = genres_df["main_genre"].str.lower()

df = df.merge(genres_df, on="main_genre")

df.tail()

MergeError: Passing 'suffixes' which cause duplicate columns {'genre_id_x'} is not allowed.

In [53]:
# add an autoincrement id 
df.insert(0, "id2", range(1, len(df) + 1))
df.head()

ValueError: cannot insert id2, already exists

In [ ]:
df = df.drop(columns=['artist_genres', 'artist_genres_list'])

In [ ]:
df.head()

In [ ]:
df.nunique()

In [ ]:
df.duplicated().sum() #no duplicates

In [ ]:
df.info() #no missing values(only in artist name but we don't need that)

In [ ]:
#created a new column with just the year
df['date'] = pd.to_datetime(df['date'], origin='1899-12-30', unit='D').dt.year
df.head()

In [ ]:
!pip install pycountry

In [ ]:
#fixing country names
import pycountry

def get_country_name(code):
    try:
        return pycountry.countries.get(alpha_2=code.upper()).name
    except:
        return code  # keeps values like 'global' unchanged

df['country'] = df['country'].apply(get_country_name)
df.head()

In [ ]:
import ast

def safe_eval_artists(s):
    try:
        return ast.literal_eval(s)
    except:
        return []
    
df['artists_list'] = df['artists'].apply(safe_eval_artists)

In [ ]:
def first_artist(artist_list):
    if artist_list:
        return artist_list[0]
    return None  # or "" if you prefer an empty string

df['artist_name'] = df['artists_list'].apply(first_artist)

In [ ]:
df.head()

In [ ]:
df.drop(columns=['artists', 'artists_list'], inplace=True)

In [ ]:
df.head()

In [ ]:
df['date'].unique()

In [ ]:
df.rename(columns={'main_genre': 'genre_name'}, inplace=True)
df.rename(columns={'track_id': 'trackID'}, inplace=True)
df.rename(columns={'name': 'title'}, inplace=True)

In [ ]:
# TESTING HYPOTHESIS1

# --- IMPORTS ---
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- PREPARE DATA ---
# Make sure your cleaned DataFrame is loaded as df
# Convert 'duration' from milliseconds to seconds if needed
df['duration_sec'] = df['duration'] / 1000

# Filter for years 2014-2022
df_analysis = df[(df['date'] >= 2014) & (df['date'] <= 2022)]

# --- AGGREGATE PER SONG ---
# Group by track_id to get average duration and total streams
song_stats = df_analysis.groupby('trackID').agg(
    avg_duration_sec=('duration_sec', 'mean'),
    total_streams=('streams', 'sum'),
    name=('title', 'first')  # Keep song title
).reset_index()

# --- SCATTER PLOT: Duration vs Total Streams ---
plt.figure(figsize=(12,6))
sns.scatterplot(data=song_stats, x='avg_duration_sec', y='total_streams')
plt.xlabel("Average Song Duration (seconds)")
plt.ylabel("Total Streams")
plt.title("Song Duration vs Total Streams (2014-2022)")
plt.show()

# --- BIN DURATION FOR AVERAGE STREAMS PER LENGTH RANGE ---
# Create bins (e.g., every 30 seconds)
bins = range(0, 601, 30)  # up to 10 min
song_stats['duration_bin'] = pd.cut(song_stats['avg_duration_sec'], bins)

# Compute average streams per bin
bin_stats = song_stats.groupby('duration_bin')['total_streams'].mean().reset_index()

# --- BAR PLOT: Average Streams per Duration Bin ---
plt.figure(figsize=(14,6))
sns.barplot(data=bin_stats, x='duration_bin', y='total_streams', palette='viridis')
plt.xticks(rotation=45)
plt.xlabel("Song Duration Bin (seconds)")
plt.ylabel("Average Total Streams")
plt.title("Average Streams by Song Duration (2014-2022)")
plt.show()

# --- OPTIONAL: CORRELATION ---
corr = song_stats['avg_duration_sec'].corr(song_stats['total_streams'])
print(f"Correlation between song duration and total streams: {corr:.2f}")

In [ ]:
#Positive correlation → longer songs tend to get more streams
#Negative correlation → shorter songs are more popular
#Near zero → no clear linear relationship

In [ ]:
# Testing hypothesis2
# Filter years if needed
df_analysis = df[(df['date'] >= 2014) & (df['date'] <= 2022)]

explicit_stats = df_analysis.groupby(['date', 'explicit']).agg(
    total_streams=('streams', 'sum'),
    avg_streams=('streams', 'mean'),
    num_songs=('trackID', 'count')
).reset_index()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))
sns.lineplot(
    data=explicit_stats,
    x='date',
    y='total_streams',
    hue='explicit',
    marker='o'
)
plt.xlabel("Year")
plt.ylabel("Total Streams")
plt.title("Total Streams: Explicit vs Non-Explicit Songs (2014-2022)")
plt.legend(title='Explicit')
plt.show()

plt.figure(figsize=(12,6))
sns.lineplot(
    data=explicit_stats,
    x='date',
    y='avg_streams',
    hue='explicit',
    marker='o'
)
plt.xlabel("Year")
plt.ylabel("Average Streams per Song")
plt.title("Average Streams per Song: Explicit vs Non-Explicit (2014-2022)")
plt.legend(title='Explicit')
plt.show()

explicit_prop = df_analysis.groupby('date')['explicit'].mean().reset_index()
explicit_prop['explicit_percent'] = explicit_prop['explicit'] * 100

plt.figure(figsize=(12,6))
sns.barplot(
    data=explicit_prop,
    x='date',
    y='explicit_percent',
    palette='coolwarm'
)
plt.xlabel("Year")
plt.ylabel("% of Songs that are Explicit")
plt.title("Trend of Explicit Songs Over Time")
plt.show()

In [ ]:
#Testing BONUS HYPOTHESIS
# Filter years 2020-2023 if desired
df_region = df[(df['date'] >= 2020) & (df['date'] <= 2023)]

regional_stats = df_region.groupby(['country', 'genre_name']).agg(
    total_streams=('streams', 'sum'),
    avg_streams=('streams', 'mean'),
    num_songs=('trackID', 'count')
).reset_index()

# Create a pivot table: countries x genres
pivot = regional_stats.pivot(index='country', columns='genre_name', values='total_streams').fillna(0)

plt.figure(figsize=(14,8))
sns.heatmap(pivot, cmap='YlGnBu', annot=True, fmt=".0f")
plt.xlabel("Genre")
plt.ylabel("Country")
plt.title("Regional Genre Popularity (Total Streams)")
plt.show()

#TOP GENRE PER COUNTRY
top_genre_country = regional_stats.loc[regional_stats.groupby('country')['total_streams'].idxmax()]
top_genre_country = top_genre_country[['country', 'genre_name', 'total_streams']].sort_values('total_streams', ascending=False)
top_genre_country.head(10)

#Proportion of streams per genre in each country
regional_stats['genre_share'] = regional_stats.groupby('country')['total_streams'].transform(lambda x: x / x.sum() * 100)

# Example: Top 5 countries for Pop
regional_stats[regional_stats['genre_name'] == 'Pop'].sort_values('genre_share', ascending=False).head(10)

In [ ]:
#df[['genre_name']].to_csv('table_genre.csv', index=False)

In [ ]:
#df[['artist_name']].to_csv('table_artist.csv', index=False)

In [ ]:
#df[['trackID', 'genre_name']].to_csv('table_track_genre.csv', index=False)

In [ ]:
#df[['trackID', 'artist_name']].to_csv('table_track_artist.csv', index=False)

In [ ]:
#df[['trackID', 'title', 'explicit', 'duration']].to_csv('table_track.csv', index=False)

In [ ]:
#f[['country', 'trackID', 'date', 'streams', 'position']].to_csv('table_charts.csv', index=False)

In [ ]:
#df[['country']].to_csv('table_country.csv', index=False)

In [ ]:
#import csv

#df.to_csv(
#   "clean_songs.csv",
#    index=False,          # no extra index column
#    sep=",",              # force comma as delimiter
#    encoding="utf-8",     # UTF-8 encoding
#    quoting=csv.QUOTE_ALL # quote all fields (prevents delimiter confusion)
)

In [ ]:
#import csv

# Select only the column you want
#df[['genre_name']].to_csv(
#    "genre_only.csv",
#    index=False,          # no extra index column
#    sep=",",              # force comma as delimiter
#    encoding="utf-8",     # UTF-8 encoding
#    quoting=csv.QUOTE_ALL # quote all fields (prevents delimiter confusion)
#)